import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { requireAdminSession } from "@/lib/auth";
import {
  getAllChallengesForAdmin,
  getChallengeAdminOverview,
} from "@/lib/challenge-admin";
import { formatDateKey } from "@/lib/utils";

export const dynamic = "force-dynamic";

type AdminChallengesPageProps = {
  searchParams?: Promise<{
    error?: string;
  }>;
};

export default async function AdminChallengesPage({ searchParams }: AdminChallengesPageProps) {
  await requireAdminSession();
  const resolvedSearchParams = await searchParams;

  const [overview, challenges] = await Promise.all([
    getChallengeAdminOverview(),
    getAllChallengesForAdmin(),
  ]);

  return (
    <div className="shell">
      <SiteHeader />

      <main className="admin-shell stack-lg">
        <section className="admin-heading">
          <div>
            <p className="eyebrow">Painel</p>
            <h1>Desafios do Arcade</h1>
          </div>

          <div className="row-actions">
            <Link href="/admin/challenges/new" className="button primary">
              Novo desafio
            </Link>
            <Link href="/admin" className="button secondary">
              Voltar ao admin
            </Link>
          </div>
        </section>

        <section className="dashboard-grid">
          <article className="dashboard-card">
            <span className="panel-label">Publicados hoje</span>
            <strong>{overview.publishedToday}</strong>
          </article>
          <article className="dashboard-card">
            <span className="panel-label">Publicados no total</span>
            <strong>{overview.totalPublished}</strong>
          </article>
          <article className="dashboard-card">
            <span className="panel-label">Rascunhos</span>
            <strong>{overview.drafts}</strong>
          </article>
        </section>

        {resolvedSearchParams?.error ? (
          <p className="error-banner">{resolvedSearchParams.error}</p>
        ) : null}

        <section className="stack-sm">
          <div className="section-heading">
            <p className="eyebrow">Agenda</p>
            <h2>Gerenciar desafios por data e categoria</h2>
          </div>

          <div className="table-shell">
            <table className="posts-table">
              <thead>
                <tr>
                  <th>Data</th>
                  <th>Categoria</th>
                  <th>Título</th>
                  <th>Status</th>
                  <th>Pontos</th>
                  <th>Ações</th>
                </tr>
              </thead>
              <tbody>
                {challenges.length > 0 ? (
                  challenges.map((challenge) => {
                    const isAutoGenerated = challenge.sourceLabel === "auto-generated";

                    return (
                    <tr key={challenge.id}>
                      <td>{formatDateKey(challenge.dateKey)}</td>
                      <td>{challenge.category}</td>
                      <td>
                        <div className="stack-xs">
                          <strong>
                            {isAutoGenerated ? "[Auto] " : ""}
                            {challenge.title}
                          </strong>
                          <span className="muted">{challenge.sourceLabel}</span>
                        </div>
                      </td>
                      <td>{challenge.status}</td>
                      <td>
                        {challenge.basePoints} x {challenge.difficulty}
                      </td>
                      <td>
                        <div className="row-actions">
                          <Link className="text-link" href={`/admin/challenges/${challenge.id}/edit`}>
                            Editar
                          </Link>
                          <form action={`/api/admin/challenges/${challenge.id}/delete`} method="post">
                            <button type="submit" className="text-button danger">
                              Excluir
                            </button>
                          </form>
                        </div>
                      </td>
                    </tr>
                    );
                  })
                ) : (
                  <tr>
                    <td colSpan={6}>
                      <div className="empty-state">
                        <p>Você ainda não cadastrou desafios no admin.</p>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </div>
  );
}
